branches:
  only:
    - master

matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.1"
      sudo: required
    - os: osx
      language: swift
      osx_image: xcode11.1
      env: SWIFT_PACKAGE_USE_COMBINEX="YES"
    - os: osx
      language: swift
      osx_image: xcode11.1
      env: TEST_COMBINE="YES"

env:
  global:
    - PROJECT="CombineX.xcodeproj"
    - SCHEME="CombineX-Package"
    - DESTINATION="platform=iOS Simulator,OS=13.1,name=iPhone 8"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)";
    fi

script:
  - if [[ $TEST_COMBINE == 'YES' ]]; then
      gem install xcpretty;
      swift package generate-xcodeproj;
      xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty;
    else
      swift test -Xswiftc -suppress-warnings;
    fi