name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'

jobs:
  mac:
    strategy:
      matrix:
        xcode_version: ['11', '11.3', '11.4', '11.5']
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
      CX_COMBINE_IMPLEMENTATION: CombineX
      CX_CONTINUOUS_INTEGRATION: "YES"
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: |
          swift -version
          swift package --version
      - name: Build and Test
        # FIXME: suppress warning for Nimble
        run: swift test -Xswiftc -suppress-warnings

  linux:
    strategy:
      matrix:
        swift_version: ['5.1', '5.2', 'latest']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: |
          swift -version
          swift package --version
      # FIXME: suppress warning for Nimble
      - name: Build and Test
        run: swift test -Xswiftc -suppress-warnings

  combine:
    runs-on: macOS-latest
    env:
      CX_COMBINE_IMPLEMENTATION: Combine
      CX_CONTINUOUS_INTEGRATION: "YES"
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: |
          sw_vers -productVersion
          swift -version
          swift package --version
      - name: Build and Test
        # FIXME: suppress warning for Nimble
        run: swift test -Xswiftc -suppress-warnings

  combine_versioning_ios:
    strategy:
      matrix:
        versions:
          # FIXME: versioning tests
          # - xcode: '11'
          #   ios: '13.0'
          # - xcode: '11.1'
          #   ios: '13.1'
          # - xcode: '11.2'
          #   ios: '13.2'
          - xcode: '11.3'
            ios: '13.3'
          - xcode: '11.4'
            ios: '13.4'
          - xcode: '11.5'
            ios: '13.5'
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.versions.xcode }}.app/Contents/Developer
      CX_COMBINE_IMPLEMENTATION: Combine
      CX_CONTINUOUS_INTEGRATION: "YES"
      PROJECT: CombineX.xcodeproj
      SCHEME: CombineX-Package
      DESTINATION: "platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.versions.ios }}"
    steps:
      - uses: actions/checkout@v1
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild test \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -destination "$DESTINATION" | xcpretty
